NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
    # подключались к главному приложению с префиксом posts/.
    path('posts/', include('NewsPortal.urls')),
]

NewsPaper/NewsPortal/urls.py
from django.urls import path
# Импортируем созданные нами представления
from .views import PostsList, PostDetail, PostCreate, PostUpdate, PostDelete

urlpatterns = [
   # path — означает путь.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   path('', PostsList.as_view(), name='posts'),
   path('search/', PostsList.as_view(), name='search'),
   path('<int:pk>/', PostDetail.as_view(), name='post'),
   path('news/create/', PostCreate.as_view(), name='news_create'),
   path('articles/create/', PostCreate.as_view(), name='articles_create'),
   path('news/<int:pk>/update/', PostUpdate.as_view(), name='news_update'),
   path('articles/<int:pk>/update/', PostUpdate.as_view(), name='articles_update'),
   path('news/<int:pk>/delete/', PostDelete.as_view(), name='news_delete'),
   path('articles/<int:pk>/delete/', PostDelete.as_view(), name='articles_delete'),
]

NewsPaper/NewsPortal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.urls import reverse


# модель авторов, содержащая метод обновления рейтинга
class Author(models.Model):
    rating = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def update_rating(self):
        posts_rating = self.posts.aggregate(pr=Coalesce(Sum('rating'), 0))['pr']
        comments_rating = self.user.comments.aggregate(cr=Coalesce(Sum('rating'), 0))['cr']
        posts_comments_rating = self.posts.aggregate(pcr=Coalesce(Sum('comment__rating'), 0))['pcr']

        self.rating = posts_rating * 3 + comments_rating + posts_comments_rating
        self.save()

# модель категорий
class Category(models.Model):
    name = models.CharField(max_length=255)
    posts = models.ManyToManyField('Post', through='PostCategory')


article = 'AR'
news = 'NE'
genres = [
    (article, 'Статья'),
    (news, 'Новость')
]

# модель постов, содержащая методы лайка, дизлайка и просмотра превью поста
class Post(models.Model):
    genre = models.CharField(max_length=2, choices=genres)
    creation = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    categories = models.ManyToManyField(Category, through='PostCategory')

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def get_absolute_url(self):
        return reverse('post', args=[str(self.id)])

# модель, реализующая связь "многие ко многим" постов и категорий
class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)

# модель комментариев, содержащая методы лайка и дизлайка
class Comment(models.Model):
    text = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/NewsPortal/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post


class PostForm(forms.ModelForm):
    text = forms.CharField(min_length=20)

    class Meta:
        model = Post
        fields = ['name', 'text', 'author', 'categories']

    def clean(self):
        cleaned_data = super().clean()
        text = cleaned_data.get("text")
        name = cleaned_data.get("name")

        if name == text:
            raise ValidationError(
                "Текст не должен быть идентичен названию."
            )

        return cleaned_data

NewsPaper/NewsPortal/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .filters import PostFilter
from .forms import PostForm
from .models import Post


# Представление для списка всех постов
class PostsList(ListView):
    # Указываем модель, объекты которой мы будем выводить
    model = Post
    # Поле, которое будет использоваться для сортировки объектов
    ordering = '-creation'
    # Указываем имя шаблона, в котором будут все инструкции о том,
    # как именно пользователю должны быть показаны наши объекты
    template_name = 'posts.html'
    # Это имя списка, в котором будут лежать все объекты.
    # Его надо указать, чтобы обратиться к списку объектов в html-шаблоне.
    context_object_name = 'posts'
    paginate_by = 10

    def get_template_names(self):
        if self.request.path == '/posts/':
            self.template_name = 'posts.html'
        elif self.request.path == '/posts/search/':
            self.template_name = 'search.html'
        return self.template_name

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        return context


# Представление для детальной информации о посте
class PostDetail(DetailView):
    # Модель всё та же, но мы хотим получать информацию по отдельному посту
    model = Post
    # Используем другой шаблон — post.html
    template_name = 'post.html'
    # Название объекта, в котором будет выбранный пользователем пост
    context_object_name = 'post'


# Представление для создания поста.
class PostCreate(CreateView):
    # Указываем нашу разработанную форму
    form_class = PostForm
    # модель постов
    model = Post
    # и новый шаблон, в котором используется форма.
    template_name = 'post_edit.html'

    # Делаем так, чтобы в зависимости от страницы у нас создавалась статья либо новость
    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/posts/articles/create/':
            post.genre = 'AR'
        elif self.request.path == '/posts/news/create/':
            post.genre = 'NE'
        return super().form_valid(form)


# Добавляем представление для изменения поста.
class PostUpdate(UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'


# Представление удаляющее пост.
class PostDelete(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('posts')

NewsPaper/templates/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим сам пост, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ post.name|censor }}</h1>
<h3>{{ post.creation|date:'d M Y' }}</h3>
<h1>{{ post.text|censor }}</h1>
{% endblock content %}

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Пост</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save" />
</form>
{% endblock content %}

NewsPaper/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{# Импортируем модуль с нашим тегом #}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   <h3>{{ posts|length }}
   <hr>
   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
               <td>Жанр</td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.name|censor }}</td>
               <td>{{ post.creation|date:'d M Y' }}</td>
                <!-- Добавим специальный фильтр truncatechars,
                чтобы ограничить количество символов до 20.
                Все остальные символы превратятся в многоточие. -->
               <td>{{ post.text|censor|truncatechars:20 }}</td>
               <td>{{ post.get_genre_display }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

   {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{# Импортируем модуль с нашим тегом #}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
   <h3>{{ posts|length }}
   <hr>
   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
               <td>Жанр</td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.name|censor }}</td>
               <td>{{ post.creation|date:'d M Y' }}</td>
                <!-- Добавим специальный фильтр truncatechars,
                чтобы ограничить количество символов до 20.
                Все остальные символы превратятся в многоточие. -->
               <td>{{ post.text|censor|truncatechars:20 }}</td>
               <td>{{ post.get_genre_display }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

   {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}